# Generated by Django 5.0 on 2024-01-08 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_post_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='slug',
        ),
        migrations.AddField(
            model_name='post',
            name='view',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
