# Generated by Django 5.0 on 2024-01-14 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_feature_technology_project_projectimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('Business', 'Business'), ('Education', 'Education'), ('Social', 'Social'), ('Organization', 'Organization')], max_length=100),
        ),
    ]
