# Generated by Django 5.0 on 2024-01-14 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_alter_project_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectimage',
            name='project',
        ),
        migrations.AddField(
            model_name='project',
            name='image',
            field=models.ManyToManyField(to='blog.projectimage'),
        ),
    ]
