# Generated by Django 5.0 on 2024-01-16 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_profile_address_profile_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='contact',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
