# Generated by Django 5.0 on 2024-01-16 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_alter_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='picture',
            field=models.ImageField(blank=True, default='default.svg', null=True, upload_to='profile_image'),
        ),
    ]
