# Generated by Django 5.0 on 2024-01-23 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_skill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='logo',
            field=models.FileField(upload_to='logos'),
        ),
    ]
