# Generated by Django 5.0 on 2024-02-25 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0025_news_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='post_url',
        ),
        migrations.RemoveField(
            model_name='news',
            name='project_url',
        ),
    ]
